#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Standalone MCP server exposing ctags/cscope symbol navigation tools."""

from __future__ import annotations

import argparse
from pathlib import Path

from mcp.server.fastmcp import FastMCP

from config import init_settings
from tools.tags_tool import find_refs as tags_find_refs
from tools.tags_tool import go_to_def as tags_go_to_def


mcp = FastMCP(
    "tsj-tags",
    instructions=(
        "Use these tools to navigate a pre-indexed C/C++ project. "
        "The project must contain tags and/or cscope.out generated by scripts/build_index.py."
    ),
)


@mcp.tool()
def go_to_def(symbol: str) -> str:
    """Find up to five definitions for a symbol using tags/cscope indexes."""
    return tags_go_to_def(symbol)


@mcp.tool()
def find_refs(symbol: str) -> str:
    """Find references for a symbol using cscope indexes."""
    return tags_find_refs(symbol)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the tsj-audit tags MCP server")
    parser.add_argument(
        "--project-path",
        default=".",
        help="Path to the audited project containing tags/cscope.out",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging for index checks",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    project_path = str(Path(args.project_path).expanduser().resolve())
    init_settings({
        "project_path": project_path,
        "debug": args.debug,
    })
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
